// <auto-generated />
using System;
using MarsRover.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarsRover.DAL.Migrations
{
    [DbContext(typeof(RoverContext))]
    [Migration("20181004081406_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarsRover.DAL.DomainData.Coordinates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RouteId");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("MarsRover.DAL.DomainData.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoverDataId");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.HasIndex("RoverDataId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("MarsRover.DAL.DomainData.RoverData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Rovers");
                });

            modelBuilder.Entity("MarsRover.DAL.DomainData.Coordinates", b =>
                {
                    b.HasOne("MarsRover.DAL.DomainData.Route", "Route")
                        .WithMany("Coordinates")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MarsRover.DAL.DomainData.Route", b =>
                {
                    b.HasOne("MarsRover.DAL.DomainData.RoverData", "Rover")
                        .WithMany("Routes")
                        .HasForeignKey("RoverDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
